#!/usr/bin/php -q
<?php

/*
 * Default vars
 */

$search = false;
$replace = false;
$source = false;
$destination = false;
$str_replace_function = 'str_replace';
$usage = <<<FOO

    usage: wpadapt [-i] -search=value -replace=value source_file target_file

    options:

      -search, -s     Required search term to replace.
                      e.g. -s=remote.domain.com

      -replace, -r    Required replacement value for the search term.
                      e.g. -r=local.domain.dev

      -i              Optional. Triggers a case-insensitive search/replace.

    examples:

      wpadapt -search=old.domain.com -replace=new.domain.dev remote_db.sql local_db.sql
      wpadapt -s=old.domain.com -f=new.domain.dev remote_db.sql local_db.sql
      wpadapt -s=OLD.DOMAIN.COM -f=new.domain.dev -i remote_db.sql local_db.sql


FOO;

/*
 * Show usage
 */

if (count($argv) === 1 || $argv[1] == '-h') {
  echo $usage;
  exit(0);
}

/*
 * Vars from args
 */

for($i = 1; $i < count($argv); $i++)
{
  $arg = $argv[$i];

  if (strpos($arg, '-search=') === 0) {
    $search = substr($arg, 8);
  }
 else if (strpos($arg, '-s=') === 0) {
    $search = substr($arg, 3);
  }
  else if (strpos($arg, '-replace=') === 0) {
    $replace = substr($arg, 9);
  }
  else if (strpos($arg, '-r=') === 0) {
    $replace = substr($arg, 3);
  }
  else if ( ! $source) {
    $source = $arg[0] == '/' ? $arg: getcwd() . '/' . $arg;
  }
  else if ( ! $destination) {
    $destination = $arg[0] == '/' ? $arg: getcwd() . '/' . $arg;
  }
  else if (strpos($arg, '-i')) {
    $str_replace_function = 'str_ireplace';
  }
}

/*
 * Validation
 */

if ( ! $search) {
  exit("\nERROR: Please provide a `-search` argument, e.g. `-search=old.domain.com`\n");
}

if ( ! $replace) {
  exit("\nERROR: Please provide a `-replace` argument, e.g. `-replace=new.domain.com`\n");
}

if ( ! $source) {
  exit("\nERROR: Please provide a source file path. (First file path)\n");
}

if ( ! $destination) {
    exit("\nERROR: Please provide a destination file path. (Second file path)\n");
}

if ( ! file_exists($source)) {
  exit("\nERROR: The source file does not exist.\nPath: $source\n");
}

/*
 * Functions
 */

function replace_urls_in_serialized($search, $replace, $string)
{
  $replaced = preg_replace_callback('/s:(\d+):([\\]*[\'"])(.*?)\2;/s', 'replace_urls_callback', $string);
  return serialize($replaced);
}

function replace_urls_callback($matches)
{
  global $str_replace_function;

  $replaced   = $str_replace_function('foo.bar.com', 'com.bar.foo', $matches[0]);
  $serialized = serialize($replaced);

  return $serialized;
}

function replace_urls_in_string($search, $replace, $string) 
{
  global $str_replace_function;

  return $str_replace_function($search, $replace, $string);
};

/*
 * Procedure
 */

$fileContents = file_get_contents($source);
$fileContents = replace_urls_in_serialized($search, $replace, $string);
$fileContents = replace_urls_in_string($search, $replace, $fileContents);

file_put_contents($destination, $fileContents);

exit(0);
